### ISSUE TITLE
Question - see the @javascript in a broweser

### ISSUE THREAD

**Issue by iefrati** [arknoll/ansible-role-selenium#25]
I use the @javascript on some of my behat testing, either to see what is going on in the browser or for some debugging.

When running behat test with selenium in a drupal vm, I do not get the browser window. Do i need to configure something unique?

my behat.local.yml is:
```
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'https://testing.test.me/'
      goutte:
        guzzle_parameters:
          verify: false
      show_cmd: open -a Safari %s
      browser_name: chrome #firefox  # Set to chrome if using the chromedriver
  suites:
    default:
      contexts:
        - FeatureContext:
            testing_hostname: 'testing.test.me'
            bootstrap_database_dump: 'init_testing.sql'
            codebase_root: '/var/www/test'
            setup_script_dir: 'var/www/test/bin'
            setup_script: 'devsite_vm_ido'
            dbusername: 'testing'
            dbpassword: 'testing'
            dbname: 'init_testing'
```
